// <auto-generated />
using System;
using BuscaMissa.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscaMissa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702030813_renomear_denuncia_para_reportar_problema")]
    partial class renomear_denuncia_para_reportar_problema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuscaMissa.Models.AvaliacaoIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("IgrejaId", "HashFingerprint")
                        .IsUnique();

                    b.ToTable("AvaliacoesIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.CodigoPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoToken")
                        .HasColumnType("int");

                    b.Property<int?>("ControleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidoAte")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ControleId");

                    b.ToTable("CodigoPermissoes");
                });

            modelBuilder.Entity("BuscaMissa.Models.ComentarioIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoBloqueio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Aprovado");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("IgrejaId", "Aprovado");

                    b.ToTable("ComentariosIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.ConfirmacaoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("IgrejaId", "HashFingerprint")
                        .IsUnique();

                    b.ToTable("ConfirmacoesHorario");
                });

            modelBuilder.Entity("BuscaMissa.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DDD")
                        .HasColumnType("longtext");

                    b.Property<string>("DDDWhatsApp")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContato")
                        .HasColumnType("longtext");

                    b.Property<bool?>("EmailContatoValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TelefoneValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelefoneWhatsApp")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TelefoneWhatsAppValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId")
                        .IsUnique();

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("BuscaMissa.Models.Contribuidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataContribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contribuidores");
                });

            modelBuilder.Entity("BuscaMissa.Models.Controle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Controles");
                });

            modelBuilder.Entity("BuscaMissa.Models.CurtidaIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoIp");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("IgrejaId", "HashFingerprint")
                        .IsUnique();

                    b.ToTable("CurtidasIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.EmailEventoIgreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DestinoContato")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EmailDestino")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Enviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDestino")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("EmailDestino");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("Tipo");

                    b.HasIndex("IgrejaId", "Tipo");

                    b.ToTable("EmailEventosIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CidadeSlug")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId")
                        .IsUnique();

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("Uf", "CidadeSlug");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("BuscaMissa.Models.EstatisticasEngajamentoIgreja", b =>
                {
                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<double>("MediaAvaliacoes")
                        .HasColumnType("double");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("int");

                    b.Property<int>("TotalCurtidas")
                        .HasColumnType("int");

                    b.Property<int>("TotalVisualizacoes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IgrejaId");

                    b.HasIndex("MediaAvaliacoes");

                    b.HasIndex("TotalCurtidas");

                    b.HasIndex("TotalVisualizacoes");

                    b.ToTable("EstatisticasEngajamentoIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Igreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GooglePlaceId")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUnico")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Paroco")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomeUnico")
                        .IsUnique()
                        .HasFilter("NomeUnico IS NOT NULL");

                    b.HasIndex("Slug");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Igrejas");
                });

            modelBuilder.Entity("BuscaMissa.Models.IgrejaReportarProblema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoRealizada")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId")
                        .IsUnique();

                    b.ToTable("IgrejaReportarProblemas");
                });

            modelBuilder.Entity("BuscaMissa.Models.IgrejaTemporaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Paroco")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IgrejaTemporarias");
                });

            modelBuilder.Entity("BuscaMissa.Models.MetricaDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TipoEntidade")
                        .HasColumnType("int");

                    b.Property<int>("TipoMetrica")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("TipoEntidade", "EntidadeId");

                    b.HasIndex("TipoEntidade", "EntidadeId", "TipoMetrica", "Data")
                        .IsUnique();

                    b.ToTable("MetricasDiarias");
                });

            modelBuilder.Entity("BuscaMissa.Models.Missa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("FontePrincipal")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time(6)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimaValidacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Missas");
                });

            modelBuilder.Entity("BuscaMissa.Models.MissaTemporaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time(6)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("MissasTemporarias");
                });

            modelBuilder.Entity("BuscaMissa.Models.RedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRedeSocial")
                        .HasColumnType("int");

                    b.Property<bool>("Verificado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("RedesSociais");
                });

            modelBuilder.Entity("BuscaMissa.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("EnviarResposta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resposta")
                        .HasColumnType("longtext");

                    b.Property<string>("Solucao")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("BuscaMissa.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AceitarPromocao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AceitarTermo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BuscaMissa.Models.VisualizacaoIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("HashFingerprint");

                    b.HasIndex("IgrejaId");

                    b.ToTable("VisualizacoesIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.AvaliacaoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.CodigoPermissao", b =>
                {
                    b.HasOne("BuscaMissa.Models.Controle", "Controle")
                        .WithMany()
                        .HasForeignKey("ControleId");

                    b.Navigation("Controle");
                });

            modelBuilder.Entity("BuscaMissa.Models.ComentarioIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.ConfirmacaoHorario", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Contato", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithOne("Contato")
                        .HasForeignKey("BuscaMissa.Models.Contato", "IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Controle", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId");

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.CurtidaIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.EmailEventoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Endereco", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithOne("Endereco")
                        .HasForeignKey("BuscaMissa.Models.Endereco", "IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.EstatisticasEngajamentoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Igreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Usuario", "Usuario")
                        .WithMany("Igrejas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BuscaMissa.Models.IgrejaReportarProblema", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithOne("ReportarProblema")
                        .HasForeignKey("BuscaMissa.Models.IgrejaReportarProblema", "IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Missa", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany("Missas")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.MissaTemporaria", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.RedeSocial", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany("RedesSociais")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.VisualizacaoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Igreja", b =>
                {
                    b.Navigation("Contato");

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Missas");

                    b.Navigation("RedesSociais");

                    b.Navigation("ReportarProblema");
                });

            modelBuilder.Entity("BuscaMissa.Models.Usuario", b =>
                {
                    b.Navigation("Igrejas");
                });
#pragma warning restore 612, 618
        }
    }
}
