// <auto-generated />
using System;
using BuscaMissa.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscaMissa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuscaMissa.Models.AvaliacaoIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("IgrejaId", "HashFingerprint")
                        .IsUnique();

                    b.ToTable("AvaliacoesIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.CodigoPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoToken")
                        .HasColumnType("int");

                    b.Property<int?>("ControleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidoAte")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ControleId");

                    b.ToTable("CodigoPermissoes");
                });

            modelBuilder.Entity("BuscaMissa.Models.ComentarioIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoBloqueio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Aprovado");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("IgrejaId", "Aprovado");

                    b.ToTable("ComentariosIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DDD")
                        .HasColumnType("longtext");

                    b.Property<string>("DDDWhatsApp")
                        .HasColumnType("longtext");

                    b.Property<string>("EmailContato")
                        .HasColumnType("longtext");

                    b.Property<bool?>("EmailContatoValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TelefoneValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TelefoneWhatsApp")
                        .HasColumnType("longtext");

                    b.Property<bool?>("TelefoneWhatsAppValidado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId")
                        .IsUnique();

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("BuscaMissa.Models.Contribuidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataContribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contribuidores");
                });

            modelBuilder.Entity("BuscaMissa.Models.Controle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Controles");
                });

            modelBuilder.Entity("BuscaMissa.Models.CurtidaIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoIp");

                    b.HasIndex("IgrejaId");

                    b.HasIndex("IgrejaId", "HashFingerprint")
                        .IsUnique();

                    b.ToTable("CurtidasIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("BuscaMissa.Models.EstatisticasEngajamentoIgreja", b =>
                {
                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MediaAvaliacoes")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalAvaliacoes")
                        .HasColumnType("int");

                    b.Property<int>("TotalComentarios")
                        .HasColumnType("int");

                    b.Property<int>("TotalCurtidas")
                        .HasColumnType("int");

                    b.Property<int>("TotalVisualizacoes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IgrejaId");

                    b.HasIndex("MediaAvaliacoes");

                    b.HasIndex("TotalCurtidas");

                    b.HasIndex("TotalVisualizacoes");

                    b.ToTable("EstatisticasEngajamentoIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Igreja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUnico")
                        .HasColumnType("longtext");

                    b.Property<string>("Paroco")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Igrejas");
                });

            modelBuilder.Entity("BuscaMissa.Models.IgrejaDenuncia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoRealizada")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailDenunciador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDenunciador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId")
                        .IsUnique();

                    b.ToTable("IgrejaDenuncias");
                });

            modelBuilder.Entity("BuscaMissa.Models.IgrejaTemporaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Paroco")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IgrejaTemporarias");
                });

            modelBuilder.Entity("BuscaMissa.Models.Missa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time(6)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("Missas");
                });

            modelBuilder.Entity("BuscaMissa.Models.MissaTemporaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time(6)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("MissasTemporarias");
                });

            modelBuilder.Entity("BuscaMissa.Models.RedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeDoPerfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoRedeSocial")
                        .HasColumnType("int");

                    b.Property<bool>("Verificado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IgrejaId");

                    b.ToTable("RedesSociais");
                });

            modelBuilder.Entity("BuscaMissa.Models.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("EnviarResposta")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Resposta")
                        .HasColumnType("longtext");

                    b.Property<string>("Solucao")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("BuscaMissa.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AceitarPromocao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AceitarTermo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BuscaMissa.Models.VisualizacaoIgreja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("HashFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IgrejaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao");

                    b.HasIndex("HashFingerprint");

                    b.HasIndex("IgrejaId");

                    b.ToTable("VisualizacoesIgreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.AvaliacaoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.CodigoPermissao", b =>
                {
                    b.HasOne("BuscaMissa.Models.Controle", "Controle")
                        .WithMany()
                        .HasForeignKey("ControleId");

                    b.Navigation("Controle");
                });

            modelBuilder.Entity("BuscaMissa.Models.ComentarioIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Contato", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithOne("Contato")
                        .HasForeignKey("BuscaMissa.Models.Contato", "IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Controle", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId");

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.CurtidaIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Endereco", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithOne("Endereco")
                        .HasForeignKey("BuscaMissa.Models.Endereco", "IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.EstatisticasEngajamentoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Igreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Usuario", "Usuario")
                        .WithMany("Igrejas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BuscaMissa.Models.IgrejaDenuncia", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithOne("Denuncia")
                        .HasForeignKey("BuscaMissa.Models.IgrejaDenuncia", "IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Missa", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany("Missas")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.MissaTemporaria", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.RedeSocial", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany("RedesSociais")
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.VisualizacaoIgreja", b =>
                {
                    b.HasOne("BuscaMissa.Models.Igreja", "Igreja")
                        .WithMany()
                        .HasForeignKey("IgrejaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Igreja");
                });

            modelBuilder.Entity("BuscaMissa.Models.Igreja", b =>
                {
                    b.Navigation("Contato");

                    b.Navigation("Denuncia");

                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Missas");

                    b.Navigation("RedesSociais");
                });

            modelBuilder.Entity("BuscaMissa.Models.Usuario", b =>
                {
                    b.Navigation("Igrejas");
                });
#pragma warning restore 612, 618
        }
    }
}
